#!/bin/bash

while true; do
	# Start ddrescue in background	
	sudo ddrescue --mapfile-interval=1m,5m -v -L -m ~/Lisa_filerecover/filerecov_domain.log /dev/sdb2 /mnt/dis_ext/Lisa/recovered/ddrescue.img /mnt/dis_ext/Lisa/ddrescue.log &

	# Make sure ddrescue has time to start
	sleep 5

	# Periodically backup log file while ddrescue is running
	while pgrep ddrescue -x > /dev/null; do
		mv /mnt/dis_ext/Lisa/ddrescue_log_backups/latest.log /mnt/dis_ext/Lisa/ddrescue_log_backups/previous.log
		cp /mnt/dis_ext/Lisa/ddrescue.log  /mnt/dis_ext/Lisa/ddrescue_log_backups/`date +"%m%d%y_%H%M%S.log"`
		cp /mnt/dis_ext/Lisa/ddrescue.log  /mnt/dis_ext/Lisa/ddrescue_log_backups/latest.log
		sleep 120
	done

	# Check if drive is alive
	if tail -n 30 /var/log/kern.log | grep DID_BAD_TARGET > /dev/null || tail -n 30 /var/log/kern.log | grep 'rejecting I/O' > /dev/null || tail -n 30 /var/log/kern.log | grep '[sdb] Stopping disk' > /dev/null; then
		echo `date +"%m-%d-%y %H:%M:%S"`' Drive offline, attempting to resurrect.'
		echo `date +"%m-%d-%y %H:%M:%S"`' Drive offline, attempting to resurrect.' >> ~/ddautorestart.log
		sudo bash -c 'echo "- - -" > /sys/class/scsi_host/host0/scan'
		echo `date +"%m-%d-%y %H:%M:%S"`' Fixing log file'
		echo `date +"%m-%d-%y %H:%M:%S"`' Fixing log file' >> ~/ddautorestart.log
		
		# Restore back to the second-to-last backup of the log file, but keep any completed blocks that occurred since
		# Note: The second-to-last backup is used because although the latest usually works fine, sometimes ddrescue takes a short period
		# of time to shutdown, and may result in the most recent backup containing invalid information (all untried sectors marked as bad)
		ddrescuelog -z /mnt/dis_ext/Lisa/ddrescue.log /mnt/dis_ext/Lisa/ddrescue_log_backups/previous.log > /mnt/dis_ext/Lisa/ddrescue.log.new
		
		# Archive the failed run's log file
		mv /mnt/dis_ext/Lisa/ddrescue.log /mnt/dis_ext/Lisa/ddrescue_bad_logs/`date +"%m%d%y_%H%M%S.log"`
		
		# Put the fixed log file into the proper location
		mv /mnt/dis_ext/Lisa/ddrescue.log.new /mnt/dis_ext/Lisa/ddrescue.log
		echo `date +"%m-%d-%y %H:%M:%S"`' Waiting 120 seconds'
		echo `date +"%m-%d-%y %H:%M:%S"`' Waiting 120 seconds' >> ~/ddautorestart.log
		sleep 120
		echo `date +"%m-%d-%y %H:%M:%S"`' Checking if drive is revived'
		echo `date +"%m-%d-%y %H:%M:%S"`' Checking if drive is revived' >> ~/ddautorestart.log
		if tail -n 30 /var/log/kern.log | grep '\[sdb\] Attached SCSI disk' > /dev/null; then
			echo `date +"%m-%d-%y %H:%M:%S"`' Drive resurrected, restarting ddrescue'
			echo `date +"%m-%d-%y %H:%M:%S"`' Drive resurrected, restarting ddrescue' >> ~/ddautorestart.log
		else
			echo `date +"%m-%d-%y %H:%M:%S"`' Failed to bring drive back online, exiting!'
			echo `date +"%m-%d-%y %H:%M:%S"`' Failed to bring drive back online, exiting!' >> ~/ddautorestart.log
			break
		fi
	else
		echo `date +"%m-%d-%y %H:%M:%S"`' ddrescue completed!'
		echo `date +"%m-%d-%y %H:%M:%S"`' ddrescue completed!' >> ~/ddautorestart.log
		break
	fi
done

exit 0 # Always return success to allow chaining with shutdown command
